# https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "website/**"
      - ".github/workflows/website.yml"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: website/package-lock.json

      - name: Build website
        run: |-
          cd website
          yarn install --frozen-lockfile
          yarn build

      # https://github.com/vercel/vercel/issues/3166#issuecomment-1508928585
      # Make sure the ./website dir exists in the github page branch, or vercel's git branch detection script won't work
      - name: Fix vercel
        run: |-
          cd website/build
          mkdir website
          touch website/.gitkeep

      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          publish_branch: gh-pages
          force_orphan: true
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
